marketpulse:                         
  target: dev                         
  outputs:

    dev:                             
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}" 
      user: "{{ env_var('SNOWFLAKE_USER') }}"    
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"  
      role: DBT_ROLE     
      database: MARKETPULSE  
      warehouse: MARKETPULSE_WH    
      schema: STAGING      
      threads: 4     
      client_session_keep_alive: False

    prod:          
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}" 
      role: DBT_ROLE
      database: MARKETPULSE
      warehouse: MARKETPULSE_WH
      schema: STAGING
      threads: 8
      client_session_keep_alive: False